### PR TITLE
Build autotools

### PR DESCRIPTION
**Pull request by JuergenKosel**
Hello,

the following changes have been made in this pull request:
- Merge with develop branch
-  Recursive Makefiles are considered harmfull, see http://aegis.sourceforge.net/auug97.pdf
  - Fixed some violations of automake conventions, regarding precompiler
    compiler and linker flags.
- Allow VPATH builds

Greetings
  Juergen

### CODE REVIEW

**Comment by guilhermeferreira** [comment]
Thank you Juergen, I'll take this weekend to test and review these changes.

**Comment by JuergenKosel** [comment]
I am not sure, but maybe you need to merge this pull request outside github, with fast-forward-merge. Otherwise the CLA check in the upstream repository may fail. Because this CLA check requires a "signed-off" line in each commit, which is not added in github´s merge commits.

Greetings
  Juergen

**Comment by JuergenKosel** [comment]
I need to redo this pull request, without the merge commit 48d1b7162e6382ba9c9724496ffdd87aecf2ccfc , because this one would lead to CLA check violation.

**Comment by guilhermeferreira** [comment]
I'll update the [build-autotools](https://github.com/guilhermeferreira/paho.mqtt.c/tree/build-autotools) branch with the latest develop changes. Then I'll cherry-pick your commits. This way you will not have to bring those extra commits.

**Pull request closed without merging**
